version: "3.7"

services:

 redis:
    image: "redis:alpine"

    command: redis-server --requirepass password2021

    ports:
     - "6379:6379"

    volumes:
     - ./redis/redis-data:/var/lib/redis

    environment:
     - REDIS_REPLICATION_MODE=master
